### ISSUE TITLE
Error after adding the dependencies

### ISSUE THREAD

**Issue by ahmedhnewa** [hfhbd/bootstrap-compose#252]
Hi, I get this error after adding the dependencies

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/73608287/182656993-3d8dbcff-aa80-499a-b590-d7991cc3f340.png">

**build.gradle.kts**

```
import org.jetbrains.compose.compose
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose")
}

group "com.example"
version "1.0-SNAPSHOT"

repositories {
    google()
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

kotlin {
    js(IR) {
        browser {
            binaries.executable()
            useCommonJs()
            commonWebpackConfig {
                cssSupport.enabled = true
            }
            testTask {
                testLogging.showStandardStreams = true
                useKarma {
                    useChromeHeadless()
                    useFirefox()
                }
            }
        }
        binaries.executable()
    }
    sourceSets {
        val jsMain by getting {
            dependencies {
                implementation(compose.web.core)
                implementation(compose.runtime)
//                implementation(npm("bootstrap", "5.2.0"))
//                implementation(npm("@popperjs/core", "2.11.5"))
                implementation("app.softwork:bootstrap-compose:0.1.6")
                implementation("app.softwork:bootstrap-compose-icons:0.1.6") // for icons support
                implementation(devNpm("sass-loader", "^13.0.0"))
                implementation(devNpm("sass", "^1.52.1"))

                implementation(npm("material-components-web", "14.0.0"))
            }
        }
        val jsTest by getting {
            dependencies {
                implementation(kotlin("test-js"))
            }
        }
    }
}

rootProject.plugins.withType<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin> {
    rootProject.the<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension>().nodeVersion = "16.0.0"
}
```

**settings.gradle.kts**

```
// Copyright 2000-2022 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }

    plugins {
        kotlin("multiplatform").version(extra["kotlin.version"] as String)
        id("org.jetbrains.compose").version(extra["compose.version"] as String)
    }
}

rootProject.name = "composeWeb"
```

**Main.kt**

```
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import app.softwork.bootstrapcompose.Alert
import app.softwork.bootstrapcompose.Color
import app.softwork.bootstrapcompose.require
import org.jetbrains.compose.web.css.*
import org.jetbrains.compose.web.dom.*
import org.jetbrains.compose.web.renderComposable
import org.w3c.dom.HTMLElement

fun main() {
    var count: Int by mutableStateOf(0)

    require("./style.scss")
    renderComposable(rootElementId = "root") {
        Alert(Color.Primary) {
            Text("Hello")
        }
    }
}
```

After removing the dependencies, the app work just fine

**Comment by hfhbd** [comment]
Hey, I can't reproduce it. Could you upload a project? Which versions of Compose and Kotlin do you use?

**Comment by ahmedhnewa** [comment]
gradle.properties:
```
kotlin.code.style=official
kotlin.native.enableDependencyPropagation=false
kotlin.js.webpack.major.version=4
kotlin.version=1.6.10
agp.version=4.2.2
compose.version=1.1.0
```

[This is the project link](https://github.com/ahmedhnewa/composeWeb)

**Comment by hfhbd** [comment]
@ahmedhnewa Thanks, reproduced. 
You are using Kotlin 1.6.10 and Compose 1.1.0. Although these are the latest stable versions of Compose, bootstrap-compose 0.1.6 uses Kotlin 1.7.0 and Compose 1.2.0-alpha01-dev741, see https://github.com/hfhbd/bootstrap-compose/releases/tag/v0.1.6

Kotlin JS (IR) is often not binary compatible. So either update your versions to Kotlin 1.7.0 and Compose to a dev version (eg the latest one: dev-753 https://github.com/JetBrains/compose-jb/releases) too, or use an older version of bootstrap-compose: https://github.com/hfhbd/bootstrap-compose/releases/tag/v0.0.51. 

Keep in mind, icons and SCSS are introduced in 0.1.1.

**Comment by ahmedhnewa** [comment]
I still get another error


```
Module build failed (from /Users/ahmedhnewa/IdeaProjects/composeWeb/build/js/node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/ahmedhnewa/IdeaProjects/composeWeb/build/js/node_modules/style-loader/dist/index.js:19:24)

✖ ｢wdm｣: Hash: 9276f5fe8277d5c5a181
Version: webpack 4.46.0
Time: 1139ms
Built at: 08/14/2022 10:11:23 PM
        Asset      Size  Chunks             Chunk Names
composeWeb.js  4.01 MiB    main  [emitted]  main
Entrypoint main = composeWeb.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./kotlin/composeWeb.js 40 bytes {main} [built]
[../../node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[../../node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[../../node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[../../node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[../../node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[../../node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[../../node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[../../node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[../../node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./kotlin/androidx-runtime.js] 979 KiB {main} [built] [106 warnings]
[./kotlin/composeWeb.js] 3.38 KiB {main} [built] [2 warnings]
[./kotlin/kotlin-kotlin-stdlib-js-ir.js] 744 KiB {main} [built] [161 warnings]
[./kotlin/style.scss] 303 bytes {main} [built] [failed] [1 error]
[./kotlin/web-internal-web-core-runtime.js] 18.8 KiB {main} [built] [10 warnings]
    + 28 hidden modules
Module build failed (from /Users/ahmedhnewa/IdeaProjects/composeWeb/build/js/node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/ahmedhnewa/IdeaProjects/composeWeb/build/js/node_modules/style-loader/dist/index.js:19:24)

✖ ｢wdm｣: Hash: 9276f5fe8277d5c5a181
Version: webpack 4.46.0
Time: 364ms
Built at: 08/14/2022 10:11:23 PM
        Asset      Size  Chunks  Chunk Names
composeWeb.js  4.01 MiB    main  main
Entrypoint main = composeWeb.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./kotlin/composeWeb.js 40 bytes {main}
[../../node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main}
[../../node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main}
[../../node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main}
[../../node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main}
[../../node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main}
[../../node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main}
[../../node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main}
[../../node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main}
[../../node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main}
[./kotlin/androidx-runtime.js] 979 KiB {main} [built] [106 warnings]
[./kotlin/composeWeb.js] 3.38 KiB {main} [built] [2 warnings]
[./kotlin/kotlin-kotlin-stdlib-js-ir.js] 744 KiB {main} [built] [161 warnings]
[./kotlin/style.scss] 303 bytes {main} [built] [failed] [1 error]
[./kotlin/web-internal-web-core-runtime.js] 18.8 KiB {main} [built] [10 warnings]
    + 28 hidden modules
```

Can you explain how to add webpack configurations because it's not so clear in the compose web documentation and in the readme of your repository

**Comment by hfhbd** [comment]
Sure, you could use the showcase (the website): https://github.com/hfhbd/bootstrap-compose/tree/main/showcase or https://github.com/hfhbd/ComposeTodo a playground app.

Why do you use web pack 4? I think this is the root problem.

And your reproducer is not available anymore, without more information and versions it is hard to help you.

**Comment by ahmedhnewa** [comment]
I just create new compose web project, I didn't change webpack version

**Comment by hfhbd** [comment]
Could you please reupload your project? Without a reproducer, it is hard to help you.
